### ISSUE TITLE
.wad files

### ISSUE THREAD

**Issue by tony--** [h4l/zwift-workout-file-reference#1]
Hi @h4l.  I'd like to extract some of the .wad files in zwift.  I saw on an old reddit thread that you were exploring that.  Did you ever make any progress?  Thanks!

**Comment by h4l** [comment]
Hey @tony-- , sorry for my delay in replying, I missed your issue here. I did make some progress — I did some investigation and wrote a quick tool to list/extract the decompressed wad files. It doesn't support the compressed wad files you find on disk though. I never published it, but I've just now made a repo for it: https://github.com/h4l/zwf. Hope that helps. I've not been keeping up to speed in this area, so I'm not sure if there are now tools to work with these files. The Zwift Coders group on FB would be a good place to ask/check.

**Comment by tony--** [comment]
Thanks @h4l!  I'll check it out.
